services:
  main-app:
    build: ./intershop-main
    ports:
      - "8080:8080"
    environment:
      PAYMENT_SERVICE_URL: http://payment-service:8081
      SPRING_PROFILES_ACTIVE: docker
      OAUTH2_CLIENT_ID: intershop-main
      OAUTH2_CLIENT_SECRET: YHPEMRyZmWGiPKMjchp250D5nZwg6hSG
      OAUTH2_TOKEN_URI: http://keycloak:8080/realms/intershop/protocol/openid-connect/token
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
    name: redis_persistent_data