spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/intershop
          jwk-set-uri: http://keycloak:8080/realms/intershop/protocol/openid-connect/certs
server:
  port: 8081
payment:
  balances:
    - userId: 1
      amount: 150000.00
    - userId: 2
      amount: 50000.00